// react/examples/Code/Router/Simple_Routing/src/Products.js
import React from 'react';

const products = [
  {id: 1, name: 'Prod 1'},
  {id: 2, name: 'Prod 2'},
  {id: 3, name: 'Prod 3'},
  {id: 4, name: 'Prod 4'},
];

function Products() {
  return (<ul className="list-group">
    { products.map((prod) => <li className="list-group-item" key={prod.id}>{prod.name}</li>)}
  </ul>);
}

export default Products;

// angular/examples/Code/Router/Route_Parameters/src/app/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductsService } from './products.service';

@Component({
  template: `
    <h1>Products</h1>
    <ul class="list-group">
      <li class="list-group-item"
        *ngFor="let product of products">
          <a [routerLink]="['/prod', product.id]">{{product.name}}</a>
        </li>
    </ul>
  `
})
export class ProductsComponent implements OnInit {
  products: Array<{ id: number; name: string; }> = [];
  constructor(private productsService: ProductsService) {}

  ngOnInit() {
    this.products = this.productsService.getProducts();
  }
}
